/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113171-g85b8d59ec7-20240102"
#endif /* AVUTIL_FFVERSION_H */
